language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

before_script:
  - cp .env.travis .env
  - echo "" >> "storage/database.sqlite"
  - echo "" >> "database/database.sqlite"
  - echo 'date.timezone = "America/SaoPaulo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install --no-interaction
  - optimize
  - php artisan key:generate

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
